version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: llm-backend
    ports:
      - "8002:8002"
    volumes:
      - ../../../airflow/data/raw:/app/data
    restart: unless-stopped
    networks:
      - llm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: llm-frontend
    ports:
      - "7862:7862"
    environment:
      - BACKEND_URL=http://backend:8002
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
